### ISSUE TITLE
`@ember/owner` Error running on Ember 3.28

### ISSUE THREAD

**Issue by elidupuis** [simonihmig/ember-stargate#677]
Just curious if anyone else has run into this. We have app running Ember 3.28 (in the process of getting to 4.0) and I'm seeing the following error after installing `ember-stargate@v0.5.0` and add couple basic portals (effectively copied from the README examples). The README still say 3.28 is supported and the [latest release](https://github.com/simonihmig/ember-stargate/releases/tag/v0.5.0) says support for 3.24 was removed.

```
Uncaught (in promise) Error: Could not find module `@ember/owner` imported from `ember-stargate/components/portal
```

After installing `ember-stargate@v0.4.3`, the above error is not an issue.

**Comment by simonihmig** [comment]
Not sure what was going on with that version. But the current one only supports Ember.js v4.12 or above, so will close this, as we won't fix issues for versions other than the latest, hope you understand!
