### ISSUE TITLE
Expose `Portal` and `PortalTarget` signatures in the exported package

### ISSUE THREAD

**Issue by didoo** [simonihmig/ember-stargate#697]
While [working on a component](https://github.com/hashicorp/design-system/pull/2102) that consumes the `Portal` and `PortalTarget` components, we wanted to use their TypeScript signatures to derive our components' ones, but with surprise we have noticed that the NPM package is not exporting the signatures:
<img width="778" alt="modified" src="https://github.com/simonihmig/ember-stargate/assets/686239/956b75c8-672b-4cce-862b-a4ba5075c368">

Any reasons why this choice? Or maybe we're doing something wrong?

**Comment by simonihmig** [comment]
First, sorry for the late response!

There is no particular reason really. Would you be willing to provide a PR maybe?

**Comment by didoo** [comment]
@simonihmig I've opened a PR for this.
