### ISSUE TITLE
Import `TrackedMap` from `tracked-built-ins` instead of `tracked-maps-and-sets`? 

### ISSUE THREAD

**Issue by johanrd** [simonihmig/ember-stargate#701]
When running [ember-addon-v2-scanner](https://github.com/IgnaceMaes/ember-addon-v2-scanner) i get a hit on one of the dependencies of ember stargate:

| NPM Name | Current version | Latest version | On V2 Addon | V2 Addon available |
|----------|:------:|------:|------:|------:|
| 'ember-stargate' | '0.6.0' | '0.6.0' | '✅'| '✅'|
|'tracked-maps-and-sets' | '3.0.2' | '3.0.2'| '❌' | '❌' |

I guess `TrackedMap` could be imported [tracked-built-ins](https://github.com/tracked-tools/tracked-built-ins) from instead of [tracked-maps-and-sets](https://github.com/tracked-tools/tracked-maps-and-sets).

From the readme, that would lose support for IE11, but that may not be entirely correct after https://github.com/tracked-tools/tracked-built-ins/pull/321?

**Comment by simonihmig** [comment]
I agree, thanks for reporting! IE11 shouldn't be an issue, given the Ember version we support here does not support IE11 either. 

A PR would be highly appreciated, if you are interested in contributing! 🙂
